### ISSUE TITLE
Bayesian optimization to tune hyperparameters coding problem.

### ISSUE THREAD

**Issue by CaiSudao** [KevinMusgrave/powerful-benchmarker#33]
python run.py --bayes_opt_iters 4 \
--loss_funcs~OVERRIDE~ {metric_loss: {MultiSimilarityLoss: {alpha~LOG_BAYESIAN~: [0.01, 100], beta~LOG_BAYESIAN~: [0.01, 100], base~BAYESIAN~: [0, 1]}}} \
--experiment_name cub_bayes_opt \

I ran this coding.It returned a mistake.

Traceback (most recent call last):
  File "run.py", line 37, in <module>
    r.run()
  File "/data/csd/anaconda3/envs/py37/lib/python3.7/site-packages/powerful_benchmarker/runners/bayes_opt_runner.py", line 121, in run
    self.create_accuracy_report(best_sub_experiment_name)
  File "/data/csd/anaconda3/envs/py37/lib/python3.7/site-packages/powerful_benchmarker/runners/bayes_opt_runner.py", line 187, in create_accuracy_report
    eval_record_group_dicts = dummy_api_parser.get_eval_record_name_dict(return_all=True)
  File "/data/csd/anaconda3/envs/py37/lib/python3.7/site-packages/powerful_benchmarker/api_parsers/base_api_parser.py", line 555, in get_eval_record_name_dict
    self.tester_obj = self.pytorch_getter.get("tester", self.args.testing_method, self.get_tester_kwargs())
  File "/data/csd/anaconda3/envs/py37/lib/python3.7/site-packages/powerful_benchmarker/api_parsers/base_api_parser.py", line 422, in get_tester_kwargs
    "data_and_label_getter": self.split_manager.data_and_label_getter,
AttributeError: 'BaseAPIParser' object has no attribute 'split_manager'

**Comment by CaiSudao** [comment]
when I use Bayesian optimization, it can't stop normal.

**Comment by CaiSudao** [comment]
what's more,  how to set the Bayesian optimization parameters of other losses?

**Comment by KevinMusgrave** [comment]
Can you check which version of the library you're using?

```python
import powerful_benchmarker
print(powerful_benchmarker.__version__)
```

**Comment by CaiSudao** [comment]
0.9.26

**Comment by KevinMusgrave** [comment]
Can you upgrade to 0.9.27? I believe that bug was fixed.
```pip install powerful_benchmarker==0.9.27```

Hopefully it'll be able to smoothly resume your current experiment. Can't guarantee it though, as there were a lot of changes between 0.9.26 and 0.9.27.

Regarding optimizing other loss functions, the syntax is exactly the same, but you change the loss name and the hyperparameter name. For example, if you want to try the TripletMarginLoss and optimize the "margin" parameter:

```
python run.py --bayes_opt_iters 50 \
--loss_funcs~OVERRIDE~ {metric_loss: {TripletMarginLoss: {margin~BAYESIAN~: [0, 1]}}} \
--experiment_name cub_bayes_opt \
```

**Comment by CaiSudao** [comment]
Thanks a lot. I will try to upgrade version to 0.9.27.
And in metric_loss: {TripletMarginLoss: {margin~BAYESIAN~: [0, 1]}  or [0, 10] will return different?

**Comment by KevinMusgrave** [comment]
Yes, the numbers inside the square brackets indicate the range of values that the bayesian optimizer will try. So if you write [0,1], then the optimizer will try values between 0 and 1, whereas if you set it to [0,10], it will try values between 0 and 10.

**Comment by CaiSudao** [comment]
So, it also needs some approximately experienced range to do Bayesian optimization. I just follow your best result to set the range.

**Comment by marijnl** [comment]
@CaiSudao can you verify after upgrading to 0.9.27 you don't get this error? 

@KevinMusgrave do you think after upgrading to 0.9.27 we can safely finish the experiment?

**Comment by KevinMusgrave** [comment]
@marijnl I don't think anything catastrophic will happen. But if you want to be safe, you could make a copy of your experiment folder first. Alternatively, if you just want to get the mean test set accuracy for your current experiment, you can open the ```bayes_opt_experiments.db``` and compute it manually. There's a table for test set accuracy, and you can copy/paste that into Excel.

**Comment by CaiSudao** [comment]
I ran the code below. And returned the TypeEorror. I don't know how to add the embedding_size argument correctly.
python run.py --bayes_opt_iters 20 \
--loss_funcs~OVERRIDE~ {metric_loss: {ArcFaceLoss: {embedding_size: 128, lr~BAYESIAN~: [0, 1], margin~BAYESIAN~: [0, 100], scale~BAYESIAN~: [0, 100]}}} \
--experiment_name bayes_opt20_ArcFaceLoss \

TypeError: __init__() missing 1 required positional argument: 'embedding_size'

**Comment by CaiSudao** [comment]
> @CaiSudao can you verify after upgrading to 0.9.27 you don't get this error?
> Yes, the code run normally.
> @KevinMusgrave do you think after upgrading to 0.9.27 we can safely finish the experiment?

**Comment by CaiSudao** [comment]
@marijnl  Yes, the code runs normally.

**Comment by marijnl** [comment]
@CaiSudao good to hear your code runs normally now :+1: 

@KevinMusgrave  I copied my experiment folder just to be sure 
After resuming the experiment i got the following stacktrace:

```
/anaconda/envs/py37_pytorch/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:1984: RuntimeWarning:

invalid value encountered in multiply

Traceback (most recent call last):
  File "benchmarker.py", line 59, in <module>
    r.run()
  File "/anaconda/envs/py37_pytorch/lib/python3.7/site-packages/powerful_benchmarker/runners/bayes_opt_runner.py", line 116, in run
    self.create_accuracy_report(best_sub_experiment_name)
  File "/anaconda/envs/py37_pytorch/lib/python3.7/site-packages/powerful_benchmarker/runners/bayes_opt_runner.py", line 219, in create_accuracy_report
    mean = np.mean(v2)
  File "<__array_function__ internals>", line 6, in mean
  File "/anaconda/envs/py37_pytorch/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 3335, in mean
    out=out, **kwargs)
  File "/anaconda/envs/py37_pytorch/lib/python3.7/site-packages/numpy/core/_methods.py", line 151, in _mean
    ret = umr_sum(arr, axis, dtype, out, keepdims)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'
```

Any idea what this could be?

**Comment by KevinMusgrave** [comment]
Hmm, I think this would happen if one or more of the accuracy metrics was used for some, but not all rows in the table. It's a valid scenario, though I'm not sure why it would happen in your case. So it might be something different going wrong. Anyway, you could try replacing [this line](https://github.com/KevinMusgrave/powerful-benchmarker/blob/master/src/powerful_benchmarker/runners/bayes_opt_runner.py#L218) with:

```python
v2 = [v3 for v3 in v1[acc_key] if v3 is not None]
```

**Comment by KevinMusgrave** [comment]
You might also want to add an if statement right after that
```python
if len(v2) == 0:
    continue
```

**Comment by marijnl** [comment]
I implemented both suggestions and it worked. Thanks!

**Comment by KevinMusgrave** [comment]
Closing for now. Also I added ```v2 = [v3 for v3 in v1[acc_key] if v3 is not None]``` and ```if(len(v2)``` to v0.9.28
